fix failing job status updates on k8s
https://github.com/Open-EO/openeo-geopyspark-driver/issues/387

Traceback (most recent call last):
  File "/opt/openeo/lib/python3.8/site-packages/openeogeotrellis/job_tracker_v2.py", line 388, in update_statuses
    self._sync_job_status(
  File "/opt/openeo/lib/python3.8/site-packages/openeogeotrellis/job_tracker_v2.py", line 516, in _sync_job_status
    usage=job_metadata.usage.to_dict(),
AttributeError: 'NoneType' object has no attribute 'to_dict'

Caused by a problem with kubecost API:

Traceback (most recent call last):
  File "/opt/openeo/lib/python3.8/site-packages/openeogeotrellis/job_tracker_v2.py", line 298, in _get_usage
    raise K8sException(
K8sException: Unexpected response {'code': 200, 'data': [{}]}