StacApiWorkspace merges regardless of "export-workspace-enable-merge" (#1507)
* StacApiWorkspace: do not require "export-workspace-enable-merge" flag #1030

* fix circular import

ImportError while importing test module '/var/lib/jenkins/workspace/_openeo-geopyspark-driver_master/tests/data_collections/test_s1backscatter_orfeo.py'.
Hint: make sure your test modules/packages have valid Python names.
Traceback:
venv38/lib64/python3.8/site-packages/_pytest/python.py:493: in importtestmodule
    mod = import_path(
venv38/lib64/python3.8/site-packages/_pytest/pathlib.py:587: in import_path
    importlib.import_module(module_name)
/usr/lib64/python3.8/importlib/__init__.py:127: in import_module
    return _bootstrap._gcd_import(name[level:], package, level)
<frozen importlib._bootstrap>:1014: in _gcd_import
    ???
<frozen importlib._bootstrap>:991: in _find_and_load
    ???
<frozen importlib._bootstrap>:975: in _find_and_load_unlocked
    ???
<frozen importlib._bootstrap>:671: in _load_unlocked
    ???
venv38/lib64/python3.8/site-packages/_pytest/assertion/rewrite.py:185: in exec_module
    exec(co, module.__dict__)
tests/data_collections/test_s1backscatter_orfeo.py:24: in <module>
    from openeogeotrellis.layercatalog import GeoPySparkLayerCatalog, get_layer_catalog
openeogeotrellis/layercatalog.py:39: in <module>
    import openeogeotrellis.backend
openeogeotrellis/backend.py:112: in <module>
    from openeogeotrellis.layercatalog import (
E   ImportError: cannot import name 'GeoPySparkLayerCatalog' from partially initialized module 'openeogeotrellis.layercatalog' (most likely due to a circular import) (/var/lib/jenkins/workspace/_openeo-geopyspark-driver_master/openeogeotrellis/layercatalog.py)

* reference python-driver with merges_by_default property #1030

* update version and CHANGELOG #1030