add sun.net.util to add-opens for unit-tests
This is required for catboost 1.2.7 with python3.11 because it complains about
```
java.lang.IllegalAccessError: class ai.catboost.spark.TrainingDriver$ (in unnamed module @0x7586beff) cannot access class sun.net.util.IPAddressUtil (in module java.base) because module java.base does not export sun.net.util to unnamed module @0x7586beff
```

ref https://github.com/eu-cdse/openeo-cdse-infra/issues/690