support bands_metadata for GTiff output assets
* use tiffset to write GDAL metadata with "role" support

https://github.com/Open-EO/openeo-geotrellis-extensions/issues/317

* encapsulate tiffset

https://github.com/Open-EO/openeo-geotrellis-extensions/issues/317

* fix tests that rely on test layer with tile size 4

The spec demands that TIFF tiles have a tile size that is a multiple of 16. We write GeoTIFFs
with a tile size that is equal to the TileLayerRDD's tile size so a tile size of 4 will produce GeoTiffs
that are not compliant. Some tools cope, like gdalinfo (with a warning), but some will simply fail,
like tiffset.

https://github.com/Open-EO/openeo-geotrellis-extensions/issues/317

* fix some tests

https://github.com/Open-EO/openeo-geotrellis-extensions/issues/317

* try workaround for tiffset segfault in container

https://github.com/Open-EO/openeo-geotrellis-extensions/issues/317

* fix tests

https://github.com/Open-EO/openeo-geotrellis-extensions/issues/317

* add TODOs

https://github.com/Open-EO/openeo-geotrellis-extensions/issues/317

* test tiffset

https://github.com/Open-EO/openeo-geotrellis-extensions/issues/317

* fix tests

https://github.com/Open-EO/openeo-geotrellis-extensions/issues/317

* fix interaction with asset-per-band

https://github.com/Open-EO/openeo-geotrellis-extensions/issues/317

* include details if tiffset fails

https://github.com/Open-EO/openeo-geotrellis-extensions/issues/317

* simplify asset-per-band mapping

https://github.com/Open-EO/openeo-geotrellis-extensions/issues/317

* tiffset is called from Scala instead + adapt/add tests

https://github.com/Open-EO/openeo-geotrellis-extensions/issues/317

* cleanup

https://github.com/Open-EO/openeo-geotrellis-extensions/issues/317

* fix tests

KeyError: DESCRIPTION

https://github.com/Open-EO/openeo-geotrellis-extensions/issues/317

* quick fix test

py4j.protocol.Py4JJavaError: An error occurred while calling z:org.openeo.geotrellis.geotiff.package.saveRDDAllowAssetPerBand.
: java.io.IOException: tiffset -sf 42112 /tmp/GDALMetadata_14266360818144674820.xml.tmp /tmp/18350960666773006729.tif failed; output was: _TIFFVSetField: /tmp/18350960666773006729.tif: Bad value 5 for "TileWidth" tag.
	at org.openeo.geotrellis.geotiff.package$.embedGdalMetadata(package.scala:940)
	at org.openeo.geotrellis.geotiff.package$.$anonfun$writeGeoTiff$2(package.scala:839)
	at org.openeo.geotrellis.geotiff.package$.$anonfun$writeGeoTiff$2$adapted(package.scala:839)
	at scala.Option.foreach(Option.scala:407)
	at org.openeo.geotrellis.geotiff.package$.writeGeoTiff(package.scala:839)
	at org.openeo.geotrellis.geotiff.package$.writeTiff(package.scala:588)
	at org.openeo.geotrellis.geotiff.package$.saveRDDGeneric(package.scala:415)
	at org.openeo.geotrellis.geotiff.package$.saveRDDAllowAssetPerBand(package.scala:254)
	at org.openeo.geotrellis.geotiff.package.saveRDDAllowAssetPerBand(package.scala)
	at jdk.internal.reflect.GeneratedMethodAccessor439.invoke(Unknown Source)
	at java.base/jdk.internal.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
	at java.base/java.lang.reflect.Method.invoke(Method.java:566)
	at py4j.reflection.MethodInvoker.invoke(MethodInvoker.java:244)
	at py4j.reflection.ReflectionEngine.invoke(ReflectionEngine.java:374)
	at py4j.Gateway.invoke(Gateway.java:282)
	at py4j.commands.AbstractCommand.invokeMethod(AbstractCommand.java:132)
	at py4j.commands.CallCommand.execute(CallCommand.java:79)
	at py4j.ClientServerConnection.waitForCommands(ClientServerConnection.java:182)
	at py4j.ClientServerConnection.run(ClientServerConnection.java:106)
	at java.base/java.lang.Thread.run(Thread.java:829)

https://github.com/Open-EO/openeo-geotrellis-extensions/issues/317

* update version and CHANGELOG

https://github.com/Open-EO/openeo-geotrellis-extensions/issues/317