don't run tests against unused Scala 2.12 jars
py4j.Py4JException: Method pyramid_seq([class geotrellis.vector.Extent,
class java.lang.String, class java.lang.String, class java.lang.String,
class java.util.ArrayList, class java.util.HashMap]) does not exist