fixed async batch jobs failing upon initialization
override default image vito-docker.artifactory.vgt.vito.be/almalinux8.5-spark-py-openeo:3.2.0

Application application_1652244279050_0191 failed 1 times (global limit =2; local limit is =1) due to AM Container for appattempt_1652244279050_0191_000001 exited with exitCode: 1
Failing this attempt.Diagnostics: [2022-05-11 08:50:52.657]Exception from container-launch.
Container id: container_e5024_1652244279050_0191_01_000001
Exit code: 1
Exception message: Launch container failed
Shell output: main : command provided 4
main : run as user is vdboschj
main : requested yarn user is vdboschj
ba1eb875244c1d0dba0ce29b8d4e4662b15840eea886378236832dfa215e77b2
Creating script paths...
Creating local dirs...
Getting exit code file...
Changing effective user to root...
Inspecting docker container...
Docker inspect command: /usr/bin/docker inspect --format {{.State.Pid}} container_e5024_1652244279050_0191_01_000001
pid from docker inspect: 19130
Writing pid file...
Writing to tmp file /data3/hadoop/yarn/local/nmPrivate/application_1652244279050_0191/container_e5024_1652244279050_0191_01_000001/container_e5024_1652244279050_0191_01_000001.pid.tmp
Waiting for docker container to finish.
Obtaining the exit code...
Docker inspect command: /usr/bin/docker inspect --format {{.State.ExitCode}} container_e5024_1652244279050_0191_01_000001
Exit code from docker inspect: 1
Wrote the exit code 1 to /data3/hadoop/yarn/local/nmPrivate/application_1652244279050_0191/container_e5024_1652244279050_0191_01_000001/container_e5024_1652244279050_0191_01_000001.pid.exitcode
[2022-05-11 08:50:52.680]Container exited with a non-zero exit code 1. Error file: prelaunch.err.
Last 4096 bytes of prelaunch.err :
Last 4096 bytes of stderr :
Error: Unable to initialize main class org.apache.spark.deploy.yarn.ApplicationMaster
Caused by: java.lang.NoClassDefFoundError: org/apache/log4j/spi/Filter
[2022-05-11 08:50:52.681]Container exited with a non-zero exit code 1. Error file: prelaunch.err.
Last 4096 bytes of prelaunch.err :
Last 4096 bytes of stderr :
Error: Unable to initialize main class org.apache.spark.deploy.yarn.ApplicationMaster
Caused by: java.lang.NoClassDefFoundError: org/apache/log4j/spi/Filter
For more detailed output, check the application tracking page: https://epod-master2.vgt.vito.be:8090/cluster/app/application_1652244279050_0191 Then click on links to logs of each attempt.
. Failing the application.