Revert "include batch request ID in poll progress logs #151 #195"
This reverts commit 5af4fd9efbe39444a7e848d70cdc87649c2c42ef.

Traceback (most recent call last):
  File "/opt/venv/lib64/python3.8/site-packages/openeogeotrellis/async_task.py", line 175, in main
    batch_jobs.poll_sentinelhub_batch_processes(job_info)
  File "/opt/venv/lib64/python3.8/site-packages/openeogeotrellis/backend.py", line 871, in poll_sentinelhub_batch_processes
    batch_processes = reduce(dict_merge_recursive,
  File "/opt/venv/lib64/python3.8/site-packages/openeogeotrellis/utils.py", line 113, in dict_merge_recursive
    raise ValueError("Can not automatically merge {a!r} and {b!r}".format(a=result[key], b=value))
ValueError: Can not automatically merge ('DONE', <function GpsBatchJobs.poll_sentinelhub_batch_processes.<locals>.batch_request_statuses.<locals>.retrier.<locals>.retry at 0x7fe3ec117700>) and ('DONE', <function GpsBatchJobs.poll_sentinelhub_batch_processes.<locals>.batch_request_statuses.<locals>.retrier.<locals>.retry at 0x7fe3ec117550>)