split off long derived from listings to separate document (#1330)
* test "derived_from" links #1278

* add comments #1278

* reuse common metadata_tracker fixture #1278

* don't break derived_from links in /jobs/<job_id>/results Collection document

https://github.com/Open-EO/openeo-geopyspark-driver/issues/1278

* support exporting item links #1278

* export file with derived_from links #1278

* link to derived_from document in batch job result items #1278

* link to derived_from document is on item instead of Collection #1278

* propagate URL to input feature for load_stac

https://github.com/Open-EO/openeo-geopyspark-driver/issues/1278

* run tests against PR jars #1278

openeo_driver.testing.ApiException: Expected response with status code 200 but got 500. Error: {'code': 'Internal', 'id': 'r-2510131109144524a702ffb1a57af274', 'message': 'load_stac: Error when constructing datacube from https://foobar.test/job/j-ec5d3e778ba5423d8d88a50b08cb9f63/results: An error occurred while calling o31732.withSelfUrl. Trace:\npy4j.Py4JException: Method withSelfUrl([class java.lang.String]) does not exist\n\tat py4j.reflection.ReflectionEngine.getMethod(ReflectionEngine.java:321)\n\tat py4j.reflection.ReflectionEngine.getMethod(ReflectionEngine.java:329)\n\tat py4j.Gateway.invoke(Gateway.java:274)\n\tat py4j.commands.AbstractCommand.invokeMethod(AbstractCommand.java:132)\n\tat py4j.commands.CallCommand.execute(CallCommand.java:79)\n\tat py4j.ClientServerConnection.waitForCommands(ClientServerConnection.java:182)\n\tat py4j.ClientServerConnection.run(ClientServerConnection.java:106)\n\tat java.base/java.lang.Thread.run(Thread.java:829)\n\n'}

* test item collection #1278

* expose Scala input feature files iso/ own from existing derived_from links #1278

* fix test_batch_job #1278

Left contains 1 more item:
  {'internal_links': []}

* Scala outputs an actual STAC item collection

https://github.com/Open-EO/openeo-geopyspark-driver/issues/1278

* make derived_from document available for download from web app #1278

* is_relative_to is Python 3.9+ #1278

* express intent better #1278

* fix 3.11 build #1278

* internal_files => auxiliary_files #1278

* put behind feature flag derived-from-document-experimental #1278

* "aux" instead of "custom" rel type #1278

* internal => auxiliary #1278

* set appropriate file permissions #1278

* returning items was addressed in PR #1242

https://github.com/Open-EO/openeo-geopyspark-driver/pull/1242
https://github.com/Open-EO/openeo-geopyspark-driver/issues/1278

* temporarily revert openeo_driver version until released #1278

* fixup! returning items was addressed in PR #1242

AttributeError: 'GpsBatchJobs' object has no attribute 'get_result_items'

* support object storage #1278

* add file: scheme #1278

* reference new constant #1278

* strengthen test #1278

* run tests against "released" 2.6.0_2.13-SNAPSHOT jars #1278

* fix default implementation of StacApiWorkspace's export_link and add test #1278

* restore suspend flag for remote debugging #1278

* adapt version and CHANGELOG #1278