whitelist "allow_empty_cubes" #649
KeyError: "Your key: allow_empty_cubes was not in the whitelist [vault_token, sentinel_hub_client_alias, max_soft_errors_ratio, dependencies, pyramid_levels, require_bounds, correlation_id, user]. This error needs to be fixed in the backend."