avoid unnecessary (risky) ETL API flow if no PUs involved
https://github.com/Open-EO/openeo-geopyspark-driver/issues/281

Traceback (most recent call last):
  File "/opt/venv/lib64/python3.8/site-packages/openeo_driver/views.py", line 624, in result
    result = backend_implementation.processing.evaluate(process_graph=process_graph, env=env)
  File "/opt/venv/lib64/python3.8/site-packages/openeo_driver/ProcessGraphDeserializer.py", line 268, in evaluate
    return evaluate(process_graph=process_graph, env=env)
  File "/opt/venv/lib64/python3.8/site-packages/openeo_driver/ProcessGraphDeserializer.py", line 333, in evaluate
    convert_node(result_node, env=env.push({ENV_DRY_RUN_TRACER: dry_run_tracer, ENV_SAVE_RESULT:[]}))
  File "/opt/venv/lib64/python3.8/site-packages/openeo_driver/ProcessGraphDeserializer.py", line 359, in convert_node
    process_result = apply_process(process_id=process_id, args=processGraph.get('arguments', {}),
  File "/opt/venv/lib64/python3.8/site-packages/openeo_driver/ProcessGraphDeserializer.py", line 1655, in apply_process
    udp = env.backend_implementation.user_defined_processes.get(user_id=user.user_id, process_id=process_id)
  File "/opt/venv/lib64/python3.8/site-packages/openeogeotrellis/user_defined_process_repository.py", line 44, in get
    with self._zk_client() as zk:
  File "/usr/lib64/python3.8/contextlib.py", line 113, in __enter__
    return next(self.gen)
  File "/opt/venv/lib64/python3.8/site-packages/openeogeotrellis/user_defined_process_repository.py", line 75, in _zk_client
    zk.start()
  File "/opt/venv/lib64/python3.8/site-packages/kazoo/client.py", line 635, in start
    raise self.handler.timeout_exception("Connection time-out")
kazoo.handlers.threading.KazooTimeoutError: Connection time-out

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "/opt/venv/lib64/python3.8/site-packages/openeogeotrellis/vault.py", line 81, in login_kerberos
    vault_token = subprocess.check_output(cmd, text=True, stderr=PIPE)
  File "/usr/lib64/python3.8/subprocess.py", line 415, in check_output
    return run(*popenargs, stdout=PIPE, timeout=timeout, check=True,
  File "/usr/lib64/python3.8/subprocess.py", line 516, in run
    raise CalledProcessError(retcode, process.args,
subprocess.CalledProcessError: Command '['vault', 'login', '-address=https://vault.vgt.vito.be', '-token-only', '-method=kerberos', 'username=openeo', 'service=vault-prod', 'realm=VGT.VITO.BE', 'keytab_path=/opt/openeo.keytab', 'krb5conf_path=/etc/krb5.conf']' returned non-zero exit status 2.

The above exception was the direct cause of the following exception:

Traceback (most recent call last):
  File "/opt/venv/lib64/python3.8/site-packages/flask/app.py", line 1516, in full_dispatch_request
    rv = self.dispatch_request()
  File "/opt/venv/lib64/python3.8/site-packages/flask/app.py", line 1502, in dispatch_request
    return self.ensure_sync(self.view_functions[rule.endpoint])(**req.view_args)
  File "/opt/venv/lib64/python3.8/site-packages/openeo_driver/users/auth.py", line 88, in decorated
    return f(*args, **kwargs)
  File "/opt/venv/lib64/python3.8/site-packages/openeo_driver/views.py", line 643, in result
    request_costs(success=False)
  File "/opt/venv/lib64/python3.8/site-packages/openeogeotrellis/backend.py", line 990, in request_costs
    return self._get_request_costs(user_id, request_id, success)
  File "/opt/venv/lib64/python3.8/site-packages/openeogeotrellis/backend.py", line 407, in get_request_costs_from_etl_api
    vault_token = vault.login_kerberos(self._principal, self._key_tab)
  File "/opt/venv/lib64/python3.8/site-packages/openeogeotrellis/vault.py", line 84, in login_kerberos
    raise VaultLoginError(
openeogeotrellis.vault.VaultLoginError: Vault login (Kerberos) failed: Command '['vault', 'login', '-address=https://vault.vgt.vito.be', '-token-only', '-method=kerberos', 'username=openeo', 'service=vault-prod', 'realm=VGT.VITO.BE', 'keytab_path=/opt/openeo.keytab', 'krb5conf_path=/etc/krb5.conf']' returned non-zero exit status 2.. stderr: "Error authenticating: couldn't log in: [Root cause: Encoding_Error] Encoding_Error: AS Exchange Error: failed to process the AS_REP < Encoding_Error: failed to unmarshal KDC's reply: asn1: syntax error: sequence truncated"