fix distracting unrelated error in stack trace
...
Caused by: java.io.EOFException
	at java.base/java.io.DataInputStream.readInt(DataInputStream.java:397)
	at org.apache.spark.api.python.PythonRunner$$anon$3.read(PythonRunner.scala:757)
	... 16 more

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "/opt/openeo/lib/python3.8/site-packages/flask/app.py", line 2073, in wsgi_app
    response = self.full_dispatch_request()
  File "/opt/openeo/lib/python3.8/site-packages/flask/app.py", line 1518, in full_dispatch_request
    rv = self.handle_user_exception(e)
  File "/opt/openeo/lib/python3.8/site-packages/flask_cors/extension.py", line 176, in wrapped_function
    return cors_after_request(app.make_response(f(*args, **kwargs)))
  File "/opt/openeo/lib/python3.8/site-packages/flask/app.py", line 1393, in handle_user_exception
    return self.ensure_sync(handler)(e)
  File "/opt/openeo/lib/python3.8/site-packages/openeo_driver/views.py", line 276, in handle_error
    error = backend_implementation.summarize_exception(error)
  File "/opt/openeo/lib/python3.8/site-packages/openeogeotrellis/backend.py", line 1316, in summarize_exception
    return self.summarize_exception_static(error, 2000)
  File "/opt/openeo/lib/python3.8/site-packages/openeogeotrellis/backend.py", line 1371, in summarize_exception_static
    udf_stacktrace = GeoPySparkBackendImplementation.extract_udf_stacktrace(root_cause_message)
  File "/opt/openeo/lib/python3.8/site-packages/openeogeotrellis/backend.py", line 1393, in extract_udf_stacktrace
    match = regex.search(full_stacktrace)
TypeError: expected string or bytes-like object