fix jar URLs
https://github.com/Open-EO/openeo-geotrellis-extensions/issues/109

INFO:get-jars:Downloading 'https://artifactory.vgt.vito.be/libs-snapshot-public/org/openeo/geotrellis-extensions/2.3.0_2.12-spark331/geotrellis-extensions-2.3.0_2.12-spark331.jar' to jars/geotrellis-extensions-2.3.0_2.12-spark331.jar
Traceback (most recent call last):
  File "scripts/get-jars.py", line 77, in <module>
    main()
  File "scripts/get-jars.py", line 69, in main
    download_jar(jar_dir, url=url, force=force_download)
  File "scripts/get-jars.py", line 30, in download_jar
    urllib.request.urlretrieve(url, target)
  File "/usr/lib64/python3.8/urllib/request.py", line 247, in urlretrieve
    with contextlib.closing(urlopen(url, data)) as fp:
  File "/usr/lib64/python3.8/urllib/request.py", line 222, in urlopen
    return opener.open(url, data, timeout)
  File "/usr/lib64/python3.8/urllib/request.py", line 531, in open
    response = meth(req, response)
  File "/usr/lib64/python3.8/urllib/request.py", line 640, in http_response
    response = self.parent.error(
  File "/usr/lib64/python3.8/urllib/request.py", line 569, in error
    return self._call_chain(*args)
  File "/usr/lib64/python3.8/urllib/request.py", line 502, in _call_chain
    result = func(*args)
  File "/usr/lib64/python3.8/urllib/request.py", line 649, in http_error_default
    raise HTTPError(req.full_url, code, msg, hdrs, fp)
urllib.error.HTTPError: HTTP Error 409: Conflict