output context of failed assembled_folder delete because the exception doesn't
INFO:__main__:removing batch jobs before 2022-05-30 01:00:12.216206...
WARNING:openeogeotrellis.backend:Could not delete unknown Sentinel Hub result folder s3://openeo-sentinelhub/0e763a47-c901-475f-bb72-330256343daf
WARNING:openeogeotrellis.backend:Could not delete unknown Sentinel Hub result folder s3://openeo-sentinelhub/a8726b8b-4931-455e-b520-3b08364afdd2
INFO:openeogeotrellis.backend:Deleted Sentinel Hub result folder(s) ['s3://openeo-sentinelhub/0e763a47-c901-475f-bb72-330256343daf', 's3://openeo-sentinelhub/a8726b8b-4931-455e-b520-3b08364afdd2'] for batch job 415e5ba0-4b43-4b50-b82f-3cede4a762a6
Traceback (most recent call last):
  File "/usr/lib64/python3.8/runpy.py", line 194, in _run_module_as_main
    return _run_code(code, main_globals, None,
  File "/usr/lib64/python3.8/runpy.py", line 87, in _run_code
    exec(code, run_globals)
  File "/opt/venv/lib64/python3.8/site-packages/openeogeotrellis/cleaner.py", line 64, in <module>
    main()
  File "/opt/venv/lib64/python3.8/site-packages/openeogeotrellis/cleaner.py", line 59, in main
    remove_batch_jobs_before(max_date, java_gateway.jvm)
  File "/opt/venv/lib64/python3.8/site-packages/openeogeotrellis/cleaner.py", line 24, in remove_batch_jobs_before
    batch_jobs.delete_jobs_before(upper)
  File "/opt/venv/lib64/python3.8/site-packages/openeogeotrellis/backend.py", line 1871, in delete_jobs_before
    self._delete_job(job_id=job_info['job_id'], user_id=job_info['user_id'], propagate_errors=True)
  File "/opt/venv/lib64/python3.8/site-packages/openeogeotrellis/backend.py", line 1802, in _delete_job
    self.delete_batch_process_dependency_sources(job_id, dependency_sources, propagate_errors)
  File "/opt/venv/lib64/python3.8/site-packages/openeogeotrellis/backend.py", line 1854, in delete_batch_process_dependency_sources
    shutil.rmtree(assembled_folder)
  File "/usr/lib64/python3.8/shutil.py", line 718, in rmtree
    _rmtree_safe_fd(fd, path, onerror)
  File "/usr/lib64/python3.8/shutil.py", line 675, in _rmtree_safe_fd
    onerror(os.unlink, fullname, sys.exc_info())
  File "/usr/lib64/python3.8/shutil.py", line 673, in _rmtree_safe_fd
    os.unlink(entry.name, dir_fd=topfd)
PermissionError: [Errno 13] Permission denied: '20180101-31UDR_7_3.tif'