EP-3963: support "load_result" in a batch job
Traceback (most recent call last):
  File "batch_job.py", line 457, in <module>
    main(sys.argv)
  File "batch_job.py", line 298, in main
    raise e
  File "batch_job.py", line 293, in main
    run_driver()
  File "batch_job.py", line 279, in run_driver
    api_version=api_version, job_dir=job_dir, dependencies=dependencies, user_id=user_id
  File "/data1/hadoop/yarn/local/usercache/vdboschj/appcache/application_1636460220092_8233/container_e5000_1636460220092_8233_01_000002/venv/lib64/python3.6/site-packages/openeogeotrellis/utils.py", line 38, in memory_logging_wrapper
    return function(*args, **kwargs)
  File "batch_job.py", line 318, in run_job
    result = ProcessGraphDeserializer.evaluate(process_graph, env=env, do_dry_run=tracer)
  File "/data1/hadoop/yarn/local/usercache/vdboschj/appcache/application_1636460220092_8233/container_e5000_1636460220092_8233_01_000002/venv/lib64/python3.6/site-packages/openeo_driver/ProcessGraphDeserializer.py", line 261, in evaluate
    return convert_node(result_node, env=env)
  File "/data1/hadoop/yarn/local/usercache/vdboschj/appcache/application_1636460220092_8233/container_e5000_1636460220092_8233_01_000002/venv/lib64/python3.6/site-packages/openeo_driver/ProcessGraphDeserializer.py", line 269, in convert_node
    namespace=processGraph.get("namespace", None), env=env
  File "/data1/hadoop/yarn/local/usercache/vdboschj/appcache/application_1636460220092_8233/container_e5000_1636460220092_8233_01_000002/venv/lib64/python3.6/site-packages/openeo_driver/ProcessGraphDeserializer.py", line 1036, in apply_process
    args = {name: convert_node(expr, env=env) for (name, expr) in sorted(args.items())}
  File "/data1/hadoop/yarn/local/usercache/vdboschj/appcache/application_1636460220092_8233/container_e5000_1636460220092_8233_01_000002/venv/lib64/python3.6/site-packages/openeo_driver/ProcessGraphDeserializer.py", line 1036, in <dictcomp>
    args = {name: convert_node(expr, env=env) for (name, expr) in sorted(args.items())}
  File "/data1/hadoop/yarn/local/usercache/vdboschj/appcache/application_1636460220092_8233/container_e5000_1636460220092_8233_01_000002/venv/lib64/python3.6/site-packages/openeo_driver/ProcessGraphDeserializer.py", line 272, in convert_node
    return convert_node(processGraph['node'], env=env)
  File "/data1/hadoop/yarn/local/usercache/vdboschj/appcache/application_1636460220092_8233/container_e5000_1636460220092_8233_01_000002/venv/lib64/python3.6/site-packages/openeo_driver/ProcessGraphDeserializer.py", line 269, in convert_node
    namespace=processGraph.get("namespace", None), env=env
  File "/data1/hadoop/yarn/local/usercache/vdboschj/appcache/application_1636460220092_8233/container_e5000_1636460220092_8233_01_000002/venv/lib64/python3.6/site-packages/openeo_driver/ProcessGraphDeserializer.py", line 1036, in apply_process
    args = {name: convert_node(expr, env=env) for (name, expr) in sorted(args.items())}
  File "/data1/hadoop/yarn/local/usercache/vdboschj/appcache/application_1636460220092_8233/container_e5000_1636460220092_8233_01_000002/venv/lib64/python3.6/site-packages/openeo_driver/ProcessGraphDeserializer.py", line 1036, in <dictcomp>
    args = {name: convert_node(expr, env=env) for (name, expr) in sorted(args.items())}
  File "/data1/hadoop/yarn/local/usercache/vdboschj/appcache/application_1636460220092_8233/container_e5000_1636460220092_8233_01_000002/venv/lib64/python3.6/site-packages/openeo_driver/ProcessGraphDeserializer.py", line 272, in convert_node
    return convert_node(processGraph['node'], env=env)
  File "/data1/hadoop/yarn/local/usercache/vdboschj/appcache/application_1636460220092_8233/container_e5000_1636460220092_8233_01_000002/venv/lib64/python3.6/site-packages/openeo_driver/ProcessGraphDeserializer.py", line 269, in convert_node
    namespace=processGraph.get("namespace", None), env=env
  File "/data1/hadoop/yarn/local/usercache/vdboschj/appcache/application_1636460220092_8233/container_e5000_1636460220092_8233_01_000002/venv/lib64/python3.6/site-packages/openeo_driver/ProcessGraphDeserializer.py", line 1036, in apply_process
    args = {name: convert_node(expr, env=env) for (name, expr) in sorted(args.items())}
  File "/data1/hadoop/yarn/local/usercache/vdboschj/appcache/application_1636460220092_8233/container_e5000_1636460220092_8233_01_000002/venv/lib64/python3.6/site-packages/openeo_driver/ProcessGraphDeserializer.py", line 1036, in <dictcomp>
    args = {name: convert_node(expr, env=env) for (name, expr) in sorted(args.items())}
  File "/data1/hadoop/yarn/local/usercache/vdboschj/appcache/application_1636460220092_8233/container_e5000_1636460220092_8233_01_000002/venv/lib64/python3.6/site-packages/openeo_driver/ProcessGraphDeserializer.py", line 272, in convert_node
    return convert_node(processGraph['node'], env=env)
  File "/data1/hadoop/yarn/local/usercache/vdboschj/appcache/application_1636460220092_8233/container_e5000_1636460220092_8233_01_000002/venv/lib64/python3.6/site-packages/openeo_driver/ProcessGraphDeserializer.py", line 269, in convert_node
    namespace=processGraph.get("namespace", None), env=env
  File "/data1/hadoop/yarn/local/usercache/vdboschj/appcache/application_1636460220092_8233/container_e5000_1636460220092_8233_01_000002/venv/lib64/python3.6/site-packages/openeo_driver/ProcessGraphDeserializer.py", line 1036, in apply_process
    args = {name: convert_node(expr, env=env) for (name, expr) in sorted(args.items())}
  File "/data1/hadoop/yarn/local/usercache/vdboschj/appcache/application_1636460220092_8233/container_e5000_1636460220092_8233_01_000002/venv/lib64/python3.6/site-packages/openeo_driver/ProcessGraphDeserializer.py", line 1036, in <dictcomp>
    args = {name: convert_node(expr, env=env) for (name, expr) in sorted(args.items())}
  File "/data1/hadoop/yarn/local/usercache/vdboschj/appcache/application_1636460220092_8233/container_e5000_1636460220092_8233_01_000002/venv/lib64/python3.6/site-packages/openeo_driver/ProcessGraphDeserializer.py", line 272, in convert_node
    return convert_node(processGraph['node'], env=env)
  File "/data1/hadoop/yarn/local/usercache/vdboschj/appcache/application_1636460220092_8233/container_e5000_1636460220092_8233_01_000002/venv/lib64/python3.6/site-packages/openeo_driver/ProcessGraphDeserializer.py", line 269, in convert_node
    namespace=processGraph.get("namespace", None), env=env
  File "/data1/hadoop/yarn/local/usercache/vdboschj/appcache/application_1636460220092_8233/container_e5000_1636460220092_8233_01_000002/venv/lib64/python3.6/site-packages/openeo_driver/ProcessGraphDeserializer.py", line 1147, in apply_process
    return process_function(args=args, env=env)
  File "/data1/hadoop/yarn/local/usercache/vdboschj/appcache/application_1636460220092_8233/container_e5000_1636460220092_8233_01_000002/venv/lib64/python3.6/site-packages/openeo_driver/ProcessGraphDeserializer.py", line 1424, in load_result
    return env.backend_implementation.load_result(job_id=job_id, user=user, load_params=load_params, env=env)
  File "/data1/hadoop/yarn/local/usercache/vdboschj/appcache/application_1636460220092_8233/container_e5000_1636460220092_8233_01_000002/venv/lib64/python3.6/site-packages/openeogeotrellis/backend.py", line 498, in load_result
    for _, asset in self.batch_jobs.get_results(job_id=job_id, user_id=user.user_id).items()
  File "/data1/hadoop/yarn/local/usercache/vdboschj/appcache/application_1636460220092_8233/container_e5000_1636460220092_8233_01_000002/venv/lib64/python3.6/site-packages/openeogeotrellis/backend.py", line 1350, in get_results
    job_info = self._get_job_info(job_id=job_id, user_id=user_id)
  File "/data1/hadoop/yarn/local/usercache/vdboschj/appcache/application_1636460220092_8233/container_e5000_1636460220092_8233_01_000002/venv/lib64/python3.6/site-packages/openeogeotrellis/backend.py", line 708, in _get_job_info
    job_info = registry.get_job(job_id, user_id)
  File "/data1/hadoop/yarn/local/usercache/vdboschj/appcache/application_1636460220092_8233/container_e5000_1636460220092_8233_01_000002/venv/lib64/python3.6/site-packages/openeogeotrellis/job_registry.py", line 186, in get_job
    job_info, _ = self._read(job_id, user_id, include_done=True)
  File "/data1/hadoop/yarn/local/usercache/vdboschj/appcache/application_1636460220092_8233/container_e5000_1636460220092_8233_01_000002/venv/lib64/python3.6/site-packages/openeogeotrellis/job_registry.py", line 275, in _read
    raise JobNotFoundException(job_id)
openeo_driver.errors.JobNotFoundException: The batch job '402d7220-7780-4a6d-b108-4eb6da436413' does not exist.