fix catboost training on YARN incl. integration test
https://github.com/eu-cdse/openeo-cdse-infra/issues/690

Traceback (most recent call last):
  File "/opt/venv/lib64/python3.11/site-packages/openeo_driver/ProcessGraphDeserializer.py", line 1965, in apply_process
    return process_function(args=ProcessArgs(args, process_id=process_id), env=env)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/opt/venv/lib64/python3.11/site-packages/openeo_driver/ProcessGraphDeserializer.py", line 1285, in fit_class_catboost
    return predictors.fit_class_catboost(target=target, iterations=iterations, depth=depth, seed=seed)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/opt/venv/lib64/python3.11/site-packages/openeogeotrellis/ml/aggregatespatialvectorcube.py", line 142, in fit_class_catboost
    model = classifier.fit(trainPool)
            ^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/opt/venv/lib64/python3.11/site-packages/openeogeotrellis/ml/catboost_spark/core.py", line 5170, in fit
    return _fit_with_eval(params)
           ^^^^^^^^^^^^^^^^^^^^^^
  File "/opt/venv/lib64/python3.11/site-packages/openeogeotrellis/ml/catboost_spark/core.py", line 5167, in _fit_with_eval
    return self._fit_with_eval(trainDatasetAsJavaObject, evalDatasetsAsJavaObject, params)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/opt/venv/lib64/python3.11/site-packages/openeogeotrellis/ml/catboost_spark/core.py", line 5124, in _fit_with_eval
    java_model = self._java_obj.fit(trainDatasetAsJavaObject, evalDatasetsAsJavaObject)
                 ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/usr/local/spark/python/lib/py4j-0.10.9.7-src.zip/py4j/java_gateway.py", line 1322, in __call__
  File "/usr/local/spark/python/lib/pyspark.zip/pyspark/errors/exceptions/captured.py", line 179, in deco
  File "/usr/local/spark/python/lib/py4j-0.10.9.7-src.zip/py4j/protocol.py", line 326, in get_return_value
py4j.protocol.Py4JJavaError: An error occurred while calling o2012.fit.
: java.lang.IllegalAccessError: class ai.catboost.spark.TrainingDriver$ (in unnamed module @0x6d8d8c28) cannot access class sun.net.util.IPAddressUtil (in module java.base) because module java.base does not export sun.net.util to unnamed module @0x6d8d8c28
	at ai.catboost.spark.TrainingDriver$.$anonfun$saveHostsListToFile$1(TrainingDriver.scala:321)
	at ai.catboost.spark.TrainingDriver$.$anonfun$saveHostsListToFile$1$adapted(TrainingDriver.scala:319)
	at scala.collection.IndexedSeqOptimized.foreach(IndexedSeqOptimized.scala:36)
	at scala.collection.IndexedSeqOptimized.foreach$(IndexedSeqOptimized.scala:33)
	at scala.collection.mutable.ArrayOps$ofRef.foreach(ArrayOps.scala:198)
	at ai.catboost.spark.TrainingDriver$.saveHostsListToFile(TrainingDriver.scala:319)
	at ai.catboost.spark.UpdatableWorkersInfo.shutdownRemainingWorkers(TrainingDriver.scala:187)
	at ai.catboost.spark.TrainingDriver.close(TrainingDriver.scala:304)
	at ai.catboost.spark.CatBoostPredictorTrait.$anonfun$fit$12(CatBoostPredictor.scala:281)
	at scala.util.control.Breaks.breakable(Breaks.scala:42)
	at ai.catboost.spark.CatBoostPredictorTrait.fit(CatBoostPredictor.scala:230)
	at ai.catboost.spark.CatBoostPredictorTrait.fit$(CatBoostPredictor.scala:125)
	at ai.catboost.spark.CatBoostClassifier.fit(CatBoostClassifier.scala:372)
	at java.base/jdk.internal.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
	at java.base/jdk.internal.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:75)
	at java.base/jdk.internal.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:52)
	at java.base/java.lang.reflect.Method.invoke(Method.java:580)
	at py4j.reflection.MethodInvoker.invoke(MethodInvoker.java:244)
	at py4j.reflection.ReflectionEngine.invoke(ReflectionEngine.java:374)
	at py4j.Gateway.invoke(Gateway.java:282)
	at py4j.commands.AbstractCommand.invokeMethod(AbstractCommand.java:132)
	at py4j.commands.CallCommand.execute(CallCommand.java:79)
	at py4j.ClientServerConnection.waitForCommands(ClientServerConnection.java:182)
	at py4j.ClientServerConnection.run(ClientServerConnection.java:106)
	at java.base/java.lang.Thread.run(Thread.java:1583)