fix load_stac: explicitly require "eo:bands" #528
   File "/opt/openeo/lib/python3.8/site-packages/openeogeotrellis/backend.py", line 893, in get_band_names
     return [get_band_name(eo_band) for eo_band in asst.extra_fields["eo:bands"]]
 KeyError: 'eo:bands'