fixed JobNotFoundException in async_task #174
Traceback (most recent call last):
  File "/opt/venv/lib64/python3.8/site-packages/openeogeotrellis/async_task.py", line 169, in main
    job_info = registry.get_job(batch_job_id, user_id)
  File "/opt/venv/lib64/python3.8/site-packages/openeogeotrellis/job_registry.py", line 187, in get_job
    job_info, _ = self._read(job_id, user_id, include_done=True)
  File "/opt/venv/lib64/python3.8/site-packages/openeogeotrellis/job_registry.py", line 279, in _read
    raise JobNotFoundException(job_id)
openeo_driver.errors.JobNotFoundException: The batch job 'j-7c7c7ca03ffb49ed9c59ef3a22b13a2b' does not exist.