fixed async_task and cleaner after pyspark upgrade
pyspark 3.2.2 depends on Py4J 0.10.9.5

Traceback (most recent call last):
  File "/opt/venv/lib64/python3.8/site-packages/openeogeotrellis/async_task.py", line 163, in main
    batch_jobs = get_batch_jobs(batch_job_id, user_id)
  File "/opt/venv/lib64/python3.8/site-packages/openeogeotrellis/async_task.py", line 134, in get_batch_jobs
    java_gateway = JavaGateway.launch_gateway(jarpath=args.py4j_jarpath,
  File "/opt/venv/lib64/python3.8/site-packages/py4j/java_gateway.py", line 2159, in launch_gateway
    _ret = launch_gateway(
  File "/opt/venv/lib64/python3.8/site-packages/py4j/java_gateway.py", line 297, in launch_gateway
    raise Py4JError("Could not find py4j jar at {0}".format(jarpath))
py4j.protocol.Py4JError: Could not find py4j jar at venv/share/py4j/py4j0.10.9.2.jar