fixup! fix job_tracker status update #1675 (#1681)
Traceback (most recent call last):
  File "/opt/openeo/lib/python3.11/site-packages/flask/app.py", line 917, in full_dispatch_request
    rv = self.dispatch_request()
         ^^^^^^^^^^^^^^^^^^^^^^^
  File "/opt/openeo/lib/python3.11/site-packages/flask/app.py", line 902, in dispatch_request
    return self.ensure_sync(self.view_functions[rule.endpoint])(**view_args)  # type: ignore[no-any-return]
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/opt/openeo/lib/python3.11/site-packages/openeo_driver/users/auth.py", line 93, in decorated
    return f(*args, **kwargs)
           ^^^^^^^^^^^^^^^^^^
  File "/opt/openeo/lib/python3.11/site-packages/openeo_driver/views.py", line 1015, in get_job_info
    return jsonify(job_info.to_api_dict(full=True, api_version=requested_api_version()))
                   ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/opt/openeo/lib/python3.11/site-packages/openeo_driver/backend.py", line 472, in to_api_dict
    usage["duration"] = {"value": int(round(self.duration.total_seconds())), "unit": "seconds"}
    ~~~~~^^^^^^^^^^^^
TypeError: 'bool' object does not support item assignment