fixed cleaner and async_task py4j dependency
Traceback (most recent call last):
  File "/usr/lib64/python3.6/runpy.py", line 193, in _run_module_as_main
    "__main__", mod_spec)
  File "/usr/lib64/python3.6/runpy.py", line 85, in _run_code
    exec(code, run_globals)
  File "/opt/scripts/OpenEO/dev/venv/lib64/python3.6/site-packages/openeogeotrellis/cleaner.py", line 61, in <module>
    main()
  File "/opt/scripts/OpenEO/dev/venv/lib64/python3.6/site-packages/openeogeotrellis/cleaner.py", line 52, in main
    die_on_exit=True)
  File "/opt/scripts/OpenEO/dev/venv/lib64/python3.6/site-packages/py4j/java_gateway.py", line 2084, in launch_gateway
    enable_auth=enable_auth)
  File "/opt/scripts/OpenEO/dev/venv/lib64/python3.6/site-packages/py4j/java_gateway.py", line 289, in launch_gateway
    raise Py4JError("Could not find py4j jar at {0}".format(jarpath))
py4j.protocol.Py4JError: Could not find py4j jar at venv/share/py4j/py4j0.10.9.2.jar

Pip's new dependency resolver fetches py4j 0.10.7 instead of 0.10.9.2; it mentioned this problem in the past:
ERROR: After October 2020 you may experience errors when installing or updating packages. This is because pip will change the way that it resolves dependency conflicts.

We recommend you use --use-feature=2020-resolver to test your packages with the new resolver before it becomes the default.

pyspark 2.3.4 requires py4j==0.10.7, but you'll have py4j 0.10.9.2 which is incompatible.