Revert "save and re-use duplicate batch requests (uncached case) #150"
This reverts commit a399bc2443cc54625be188b527714ec4d8cd83e2.

[2022-04-27 15:29:21,981] ERROR in openeo_driver.views: [Lorg.locationtech.jts.geom.MultiPolygon;@17500326
Traceback (most recent call last):
  File "/opt/venv/lib64/python3.8/site-packages/flask/app.py", line 1516, in full_dispatch_request
    rv = self.dispatch_request()
  File "/opt/venv/lib64/python3.8/site-packages/flask/app.py", line 1502, in dispatch_request
    return self.ensure_sync(self.view_functions[rule.endpoint])(**req.view_args)
  File "/opt/venv/lib64/python3.8/site-packages/openeo_driver/users/auth.py", line 88, in decorated
    return f(*args, **kwargs)
  File "/opt/venv/lib64/python3.8/site-packages/openeo_driver/views.py", line 801, in queue_job
    backend_implementation.batch_jobs.start_job(job_id=job_id, user=user)
  File "/opt/venv/lib64/python3.8/site-packages/openeogeotrellis/backend.py", line 900, in start_job
    self._start_job(job_id, user.user_id)
  File "/opt/venv/lib64/python3.8/site-packages/openeogeotrellis/backend.py", line 928, in _start_job
    and self._scheduled_sentinelhub_batch_processes(spec['process_graph'], api_version, registry,
  File "/opt/venv/lib64/python3.8/site-packages/openeogeotrellis/backend.py", line 1411, in _scheduled_sentinelhub_batch_processes
    batch_request_cache_key = to_hashable(uncached_batch_request_args)
  File "/opt/venv/lib64/python3.8/site-packages/openeo_driver/utils.py", line 177, in to_hashable
    return tuple(to_hashable(x) for x in obj)
  File "/opt/venv/lib64/python3.8/site-packages/openeo_driver/utils.py", line 177, in <genexpr>
    return tuple(to_hashable(x) for x in obj)
  File "/opt/venv/lib64/python3.8/site-packages/openeo_driver/utils.py", line 183, in to_hashable
    raise ValueError(obj)
ValueError: [Lorg.locationtech.jts.geom.MultiPolygon;@17500326