fix removal of multiple original assets
* debug multiple assets #883

* fix removal of multiple original assets #883

Traceback (most recent call last):
  File "/opt/openeo/lib/python3.8/site-packages/openeogeotrellis/deploy/batch_job.py", line 736, in start_main
    main(sys.argv)
  File "/opt/openeo/lib/python3.8/site-packages/openeogeotrellis/deploy/batch_job.py", line 245, in main
    run_driver()
  File "/opt/openeo/lib/python3.8/site-packages/openeogeotrellis/deploy/batch_job.py", line 206, in run_driver
    run_job(
  File "/opt/openeo/lib/python3.8/site-packages/openeogeotrellis/utils.py", line 57, in memory_logging_wrapper
    return function(*args, **kwargs)
  File "/opt/openeo/lib/python3.8/site-packages/openeogeotrellis/deploy/batch_job.py", line 486, in run_job
    _export_to_workspaces(
  File "/opt/openeo/lib/python3.8/site-packages/openeogeotrellis/deploy/batch_job.py", line 567, in _export_to_workspaces
    export_to_workspace(source_uri=stac_href)
  File "/opt/openeo/lib/python3.8/site-packages/openeogeotrellis/deploy/batch_job.py", line 591, in _export_to_workspace
    return target.import_file(Path(uri_parts.path), merge, remove_original)
  File "/opt/openeo/lib/python3.8/site-packages/openeogeotrellis/workspace.py", line 22, in import_file
    s3_client().upload_file(str(file), self.bucket, key)
  File "/opt/openeo/lib/python3.8/site-packages/boto3/s3/inject.py", line 129, in upload_file
    return transfer.upload_file(
  File "/opt/openeo/lib/python3.8/site-packages/boto3/s3/transfer.py", line 279, in upload_file
    future.result()
  File "/opt/openeo/lib/python3.8/site-packages/s3transfer/futures.py", line 106, in result
    return self._coordinator.result()
  File "/opt/openeo/lib/python3.8/site-packages/s3transfer/futures.py", line 265, in result
    raise self._exception
  File "/opt/openeo/lib/python3.8/site-packages/s3transfer/tasks.py", line 255, in _main
    self._submit(transfer_future=transfer_future, **kwargs)
  File "/opt/openeo/lib/python3.8/site-packages/s3transfer/upload.py", line 549, in _submit
    upload_input_manager.provide_transfer_size(transfer_future)
  File "/opt/openeo/lib/python3.8/site-packages/s3transfer/upload.py", line 236, in provide_transfer_size
    self._osutil.get_file_size(
  File "/opt/openeo/lib/python3.8/site-packages/s3transfer/utils.py", line 245, in get_file_size
    return os.path.getsize(filename)
  File "/usr/lib64/python3.8/genericpath.py", line 50, in getsize
    return os.stat(filename).st_size
FileNotFoundError: [Errno 2] No such file or directory: '/batch_jobs/j-2411074401df4dc385b96453257713cf/openEO_2023-06-04Z.tif.json'

* cleanup #883

* update version and CHANGELOG #883