avoid instantiating EJR in batch job if web app does not have one configured #1005
jinja2 renders None as "None", causing implicit EJR instantiation in a batch job; this instantiation fails because there are no valid EJR credentials.

Traceback (most recent call last):
  File "/opt/openeo/lib/python3.8/site-packages/openeogeotrellis/deploy/batch_job.py", line 866, in start_main
    main(sys.argv)
  File "/opt/openeo/lib/python3.8/site-packages/openeogeotrellis/deploy/batch_job.py", line 246, in main
    run_driver()
  File "/opt/openeo/lib/python3.8/site-packages/openeogeotrellis/deploy/batch_job.py", line 207, in run_driver
    run_job(
  File "/opt/openeo/lib/python3.8/site-packages/openeogeotrellis/utils.py", line 67, in memory_logging_wrapper
    return function(*args, **kwargs)
  File "/opt/openeo/lib/python3.8/site-packages/openeogeotrellis/deploy/batch_job.py", line 297, in run_job
    backend_implementation = GeoPySparkBackendImplementation(
  File "/opt/openeo/lib/python3.8/site-packages/openeogeotrellis/backend.py", line 373, in __init__
    elastic_job_registry = get_elastic_job_registry(
  File "/opt/openeo/lib/python3.8/site-packages/openeogeotrellis/backend.py", line 1463, in get_elastic_job_registry
    ejr_creds = get_ejr_credentials_from_env(strict=True)
  File "/opt/openeo/lib/python3.8/site-packages/openeo_driver/jobregistry.py", line 268, in get_ejr_credentials_from_env
    creds = ClientCredentials.from_credentials_string(
  File "/opt/openeo/lib/python3.8/site-packages/openeo_driver/util/auth.py", line 61, in from_credentials_string
    raise ValueError(f"Failed parsing {cls.__name__} from credentials string")
ValueError: Failed parsing ClientCredentials from credentials string