fixed SHub sync calls in the context of a batch job
Lost task 0.0 in stage 1.0 (TID 1, epod110.vgt.vito.be, executor 1):
java.lang.IllegalStateException: Cannot invoke rate-limiting guard process
because PYSPARK_PYTHON is not set