EP-3869: fixed AccessDeniedException for openeo_collecting
Subdirectories inherit /tmp_epod/openeo_collecting's
group (eodata) because of its setgid flag;
both driver and JobTracker need write permissions.

Traceback (most recent call last):
  File "/opt/scripts/OpenEO/venv/lib64/python3.6/site-packages/openeogeotrellis/job_tracker.py", line 79, in update_statuses
    if self._batch_jobs.poll_sentinelhub_batch_processes(job_info):
  File "/opt/scripts/OpenEO/venv/lib64/python3.6/site-packages/openeogeotrellis/backend.py", line 615, in poll_sentinelhub_batch_processes
    caching_service.download_and_cache_results(bucket_name, subfolder, collecting_folder)
  File "/opt/scripts/OpenEO/venv/lib64/python3.6/site-packages/py4j/java_gateway.py", line 1310, in __call__
    answer, self.gateway_client, self.target_id, self.name)
  File "/opt/scripts/OpenEO/venv/lib64/python3.6/site-packages/py4j/protocol.py", line 328, in get_return_value
    format(target_id, ".", name), value)
py4j.protocol.Py4JJavaError: An error occurred while calling o4.download_and_cache_results.
: java.nio.file.AccessDeniedException: /tmp_epod/openeo_collecting/collecting__l4_0tgi/31UDS_7_2-20190921-B04.tif
	at sun.nio.fs.UnixException.translateToIOException(UnixException.java:84)
	at sun.nio.fs.UnixException.rethrowAsIOException(UnixException.java:102)
	at sun.nio.fs.UnixException.rethrowAsIOException(UnixException.java:107)
	at sun.nio.fs.UnixFileSystemProvider.createSymbolicLink(UnixFileSystemProvider.java:457)
	at java.nio.file.Files.createSymbolicLink(Files.java:1043)
	at org.openeo.geotrellissentinelhub.CachingService$$anonfun$download_and_cache_results$1$$anonfun$apply$1.apply(CachingService.scala:62)
	at org.openeo.geotrellissentinelhub.CachingService$$anonfun$download_and_cache_results$1$$anonfun$apply$1.apply(CachingService.scala:60)
	at scala.Option.foreach(Option.scala:257)
	at org.openeo.geotrellissentinelhub.CachingService$$anonfun$download_and_cache_results$1.apply(CachingService.scala:60)
	at org.openeo.geotrellissentinelhub.CachingService$$anonfun$download_and_cache_results$1.apply(CachingService.scala:57)
	at org.openeo.geotrellissentinelhub.S3Service$$anonfun$downloadBatchProcessResults$1$$anonfun$apply$3$$anonfun$apply$5.apply(S3Service.scala:145)
	at org.openeo.geotrellissentinelhub.S3Service$$anonfun$downloadBatchProcessResults$1$$anonfun$apply$3$$anonfun$apply$5.apply(S3Service.scala:139)
	at scala.collection.TraversableLike$WithFilter$$anonfun$foreach$1.apply(TraversableLike.scala:733)
	at scala.collection.immutable.List.foreach(List.scala:381)
	at scala.collection.TraversableLike$WithFilter.foreach(TraversableLike.scala:732)
	at org.openeo.geotrellissentinelhub.S3Service$$anonfun$downloadBatchProcessResults$1$$anonfun$apply$3.apply(S3Service.scala:139)
	at org.openeo.geotrellissentinelhub.S3Service$$anonfun$downloadBatchProcessResults$1$$anonfun$apply$3.apply(S3Service.scala:127)
	at scala.collection.mutable.ResizableArray$class.foreach(ResizableArray.scala:59)
	at scala.collection.mutable.ArrayBuffer.foreach(ArrayBuffer.scala:48)
	at org.openeo.geotrellissentinelhub.S3Service$$anonfun$downloadBatchProcessResults$1.apply(S3Service.scala:127)
	at org.openeo.geotrellissentinelhub.S3Service$$anonfun$downloadBatchProcessResults$1.apply(S3Service.scala:118)
	at org.openeo.geotrellissentinelhub.S3Service.withS3Client(S3Service.scala:30)
	at org.openeo.geotrellissentinelhub.S3Service.downloadBatchProcessResults(S3Service.scala:118)
	at org.openeo.geotrellissentinelhub.CachingService.download_and_cache_results(CachingService.scala:52)
	at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
	at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62)
	at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
	at java.lang.reflect.Method.invoke(Method.java:498)
	at py4j.reflection.MethodInvoker.invoke(MethodInvoker.java:244)
	at py4j.reflection.ReflectionEngine.invoke(ReflectionEngine.java:357)
	at py4j.Gateway.invoke(Gateway.java:282)
	at py4j.commands.AbstractCommand.invokeMethod(AbstractCommand.java:132)
	at py4j.commands.CallCommand.execute(CallCommand.java:79)
	at py4j.GatewayConnection.run(GatewayConnection.java:238)
	at java.lang.Thread.run(Thread.java:748)