fixed KeyError: 'providers' upon loading catalog in async_task
Enrichment restores the "providers" property that was recently removed from SENTINEL2_L2A_SENTINELHUB in layercatalog.json.

failed to handle polling batch job a4ac139c-c137-4ee4-81e6-44678af02acf:
Traceback (most recent call last):
  File "/opt/scripts/OpenEO/dev2/venv/lib/python3.8/site-packages/openeogeotrellis/async_task.py", line 160, in main
    batch_jobs().poll_sentinelhub_batch_processes(job_info)
  File "/opt/scripts/OpenEO/dev2/venv/lib/python3.8/site-packages/openeogeotrellis/async_task.py", line 133, in batch_jobs
    return GpsBatchJobs(get_layer_catalog(opensearch_enrich=False), java_gateway.jvm, args.principal,
  File "/opt/scripts/OpenEO/dev2/venv/lib/python3.8/site-packages/openeogeotrellis/layercatalog.py", line 624, in get_layer_catalog
    metadata = _merge_layers_with_common_name(metadata)
  File "/opt/scripts/OpenEO/dev2/venv/lib/python3.8/site-packages/openeogeotrellis/layercatalog.py", line 641, in _merge_layers_with_common_name
    new_metadata["providers"] += common_name_metadata["providers"]
KeyError: 'providers'