missing metrics are not exceptional for short jobs #396
Traceback (most recent call last):
  File "/opt/openeo/lib/python3.8/site-packages/openeogeotrellis/job_tracker_v2.py", line 285, in _get_usage
    byte_seconds = prometheus.get_memory_usage(application_id, application_duration_s)
  File "/opt/openeo/lib/python3.8/site-packages/openeogeotrellis/integrations/prometheus.py", line 44, in get_memory_usage
    return self._query_for_value(query, at)
  File "/opt/openeo/lib/python3.8/site-packages/openeogeotrellis/integrations/prometheus.py", line 22, in _query_for_value
    value = float(resp.json()['data']['result'][0]['value'][1])
IndexError: list index out of range