get results metadata from disk/object storage (#1260)
* outline read work #1255

* outline write work #1255

* add TODOs #1255

* persist and retrieve job's results_metadata_uri #1255

* avoid implementation detail results_metadata_uri in API #1255

* test persisting results_metadata_uri #1255

* test reading s3:// results_metadata_uri #1255

* test reading file:// results_metadata_uri #1255

* fix test on Jenkins #1255

AttributeError: 'called_once' is not a valid assertion. Use a spec for the mock if 'called_once' is meant to be an attribute.

* fix remaining tests #1255

* test remaining getters #1255

* a job not having the chance to write job_metadata.json yet is not exceptional

https://github.com/Open-EO/openeo-geopyspark-driver/issues/1255

* fix false negative #1255

Still looked in own bucket instead of the one in results_metadata_uri.

* do not patch all results metadata into job registry #1255

* reference Python driver with support for results_metadata_uri #1255

* adapt version and CHANGELOG #1255 #1200

* address TODOs #1255 #1200

* remove unnecessary test case #1255

* address review remarks #1255