fixed fetching access token in async task
Traceback (most recent call last):
  File "/opt/scripts/OpenEO/dev/venv/lib/python3.8/site-packages/openeogeotrellis/async_task.py", line 164, in main
    batch_jobs().poll_sentinelhub_batch_processes(job_info)
  File "/opt/scripts/OpenEO/dev/venv/lib/python3.8/site-packages/openeogeotrellis/backend.py", line 755, in poll_sentinelhub_batch_processes
    statuses = reduce(operator.add, (batch_request_statuses(dependency) for dependency in dependencies))
  File "/opt/scripts/OpenEO/dev/venv/lib/python3.8/site-packages/openeogeotrellis/backend.py", line 755, in <genexpr>
    statuses = reduce(operator.add, (batch_request_statuses(dependency) for dependency in dependencies))
  File "/opt/scripts/OpenEO/dev/venv/lib/python3.8/site-packages/openeogeotrellis/backend.py", line 750, in batch_request_statuses
    return [(batch_processing_service.get_batch_process_status(request_id) if request_id else "DONE",
  File "/opt/scripts/OpenEO/dev/venv/lib/python3.8/site-packages/openeogeotrellis/backend.py", line 750, in <listcomp>
    return [(batch_processing_service.get_batch_process_status(request_id) if request_id else "DONE",
  File "/opt/scripts/OpenEO/dev/venv/lib/python3.8/site-packages/py4j/java_gateway.py", line 1309, in __call__
    return_value = get_return_value(
  File "/opt/scripts/OpenEO/dev/venv/lib/python3.8/site-packages/py4j/protocol.py", line 326, in get_return_value
    raise Py4JJavaError(
py4j.protocol.Py4JJavaError: An error occurred while calling o0.get_batch_process_status.
: java.lang.IllegalStateException: Cannot invoke rate-limiting guard process because PYSPARK_PYTHON is not set
	at org.openeo.geotrellissentinelhub.RlGuardAdapter.call(RateLimitingGuard.scala:77)
	at org.openeo.geotrellissentinelhub.RlGuardAdapter.accessToken(RateLimitingGuard.scala:69)
	at org.openeo.geotrellissentinelhub.MemoizedRlGuardAdapterCachedAccessTokenWithAuthApiFallbackAuthorizer.$anonfun$authorized$1(Authorizer.scala:30)
	at scala.compat.java8.functionConverterImpls.AsJavaFunction.apply(FunctionConverters.scala:262)
	at com.github.benmanes.caffeine.cache.BoundedLocalCache.lambda$doComputeIfAbsent$14(BoundedLocalCache.java:2344)
	at java.util.concurrent.ConcurrentHashMap.compute(ConcurrentHashMap.java:1853)
	at com.github.benmanes.caffeine.cache.BoundedLocalCache.doComputeIfAbsent(BoundedLocalCache.java:2342)
	at com.github.benmanes.caffeine.cache.BoundedLocalCache.computeIfAbsent(BoundedLocalCache.java:2325)
	at com.github.benmanes.caffeine.cache.LocalCache.computeIfAbsent(LocalCache.java:108)
	at com.github.benmanes.caffeine.cache.LocalManualCache.get(LocalManualCache.java:62)
	at com.github.blemale.scaffeine.Cache.get(Cache.scala:40)
	at org.openeo.geotrellissentinelhub.AccessTokenCache$.get(Authorizer.scala:103)
	at org.openeo.geotrellissentinelhub.MemoizedRlGuardAdapterCachedAccessTokenWithAuthApiFallbackAuthorizer.accessToken$1(Authorizer.scala:27)
	at org.openeo.geotrellissentinelhub.MemoizedRlGuardAdapterCachedAccessTokenWithAuthApiFallbackAuthorizer.authorized(Authorizer.scala:46)
	at org.openeo.geotrellissentinelhub.BatchProcessingService.authorized(BatchProcessingService.scala:24)
	at org.openeo.geotrellissentinelhub.BatchProcessingService.get_batch_process_status(BatchProcessingService.scala:136)
	at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
	at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62)
	at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
	at java.lang.reflect.Method.invoke(Method.java:498)
	at py4j.reflection.MethodInvoker.invoke(MethodInvoker.java:244)
	at py4j.reflection.ReflectionEngine.invoke(ReflectionEngine.java:357)
	at py4j.Gateway.invoke(Gateway.java:282)
	at py4j.commands.AbstractCommand.invokeMethod(AbstractCommand.java:132)
	at py4j.commands.CallCommand.execute(CallCommand.java:79)
	at py4j.GatewayConnection.run(GatewayConnection.java:238)
	at java.lang.Thread.run(Thread.java:748)