Issue #227 add more logging around mask crs handling
current failure in the #227 use case is related to mask retiling:
    ValueError: The layout needs to have the same crs as the TiledRasterLayer