EP-4035: fixed call to delete SHub batch results in S3
An error occurred while calling o0.delete_batch_process_dependency_sources. Trace:
py4j.Py4JException: Method delete_batch_process_dependency_sources([class java.lang.String, class java.lang.String]) does not exist
	at py4j.reflection.ReflectionEngine.getMethod(ReflectionEngine.java:318)
	at py4j.reflection.ReflectionEngine.getMethod(ReflectionEngine.java:326)
	at py4j.Gateway.invoke(Gateway.java:274)
	at py4j.commands.AbstractCommand.invokeMethod(AbstractCommand.java:132)
	at py4j.commands.CallCommand.execute(CallCommand.java:79)
	at py4j.GatewayConnection.run(GatewayConnection.java:238)
	at java.lang.Thread.run(Thread.java:748)

", "exc_info": "Traceback (most recent call last):
  File "/opt/scripts/OpenEO/dev/venv/lib64/python3.6/site-packages/openeogeotrellis/async_task.py", line 143, in main
    propagate_errors=True)
  File "/opt/scripts/OpenEO/dev/venv/lib64/python3.6/site-packages/openeogeotrellis/backend.py", line 1415, in delete_batch_process_dependency_sources
    s3_service.delete_batch_process_dependency_sources(bucket_name, subfolder)
  File "/opt/scripts/OpenEO/dev/venv/lib64/python3.6/site-packages/py4j/java_gateway.py", line 1310, in __call__
    answer, self.gateway_client, self.target_id, self.name)
  File "/opt/scripts/OpenEO/dev/venv/lib64/python3.6/site-packages/py4j/protocol.py", line 332, in get_return_value
    format(target_id, ".", name, value))
py4j.protocol.Py4JError: An error occurred while calling o0.delete_batch_process_dependency_sources. Trace:
py4j.Py4JException: Method delete_batch_process_dependency_sources([class java.lang.String, class java.lang.String]) does not exist
	at py4j.reflection.ReflectionEngine.getMethod(ReflectionEngine.java:318)
	at py4j.reflection.ReflectionEngine.getMethod(ReflectionEngine.java:326)
	at py4j.Gateway.invoke(Gateway.java:274)
	at py4j.commands.AbstractCommand.invokeMethod(AbstractCommand.java:132)
	at py4j.commands.CallCommand.execute(CallCommand.java:79)
	at py4j.GatewayConnection.run(GatewayConnection.java:238)
	at java.lang.Thread.run(Thread.java:748)